apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cost-mgmt-data.openshift.io/v1alpha1",
          "kind": "CostManagementData",
          "metadata": {
            "name": "cost-mgmt-data-example"
          }
        },
        {
          "apiVersion": "cost-mgmt.openshift.io/v1alpha1",
          "kind": "CostManagement",
          "metadata": {
            "name": "cost-mgmt-setup"
          },
          "spec": {
            "authentication_secret_name": "auth-secret-name-placeholder",
            "clusterID": "cluster-id-placeholder",
            "reporting_operator_token_name": "reporting-operator-token-placeholder",
            "validate_cert": "false"
          }
        }
      ]
    capabilities: Basic Install
  name: cost-mgmt-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Cost Management resource
      displayName: CostManagement
      kind: CostManagement
      name: costmanagements.cost-mgmt.openshift.io
      version: v1alpha1
    - description: Cost Management Data resource
      displayName: CostManagementData
      kind: CostManagementData
      name: cost-mgmt-data.cost-mgmt-data.openshift.io
      version: v1alpha1
    required:
    - description: Cost Management resource
      displayName: CostManagement
      kind: CostManagement
      name: costmanagements.cost-mgmt.openshift.io
      version: v1alpha1
    - description: Cost Management Data resource
      displayName: CostManagementData
      kind: CostManagementData
      name: cost-mgmt-data.cost-mgmt-data.openshift.io
      version: v1alpha1
    - description: An instance of Metering with high-level configuration
      displayName: Metering Configuration
      kind: MeteringConfig
      name: meteringconfigs.metering.openshift.io
      version: v1
    - description: A scheduled or on-off Metering Report summarizes data based on
        the query specified.
      displayName: Metering Report
      kind: Report
      name: reports.metering.openshift.io
      version: v1
    - description: A SQL query used by Metering to generate reports.
      displayName: Metering Report Query
      kind: ReportQuery
      name: reportqueries.metering.openshift.io
      version: v1
    - description: Used under-the-hood. A resource representing a database table in
        Presto. Used by ReportQueries to determine what tables exist, and by the HTTP
        API to determine how to query a table.
      displayName: Metering Data Source
      kind: ReportDataSource
      name: reportdatasources.metering.openshift.io
      version: v1
    - description: Represents a configurable storage location for Metering to store
        metering and report data.
      displayName: Metering Storage Location
      kind: StorageLocation
      name: storagelocations.metering.openshift.io
      version: v1
    - description: Used under-the-hood. A resource describing a source of data for
        usage by Report Queries.
      displayName: Metering Presto Table
      kind: PrestoTable
      name: prestotables.metering.openshift.io
      version: v1
    - description: Used under-the-hood. A resource representing a database table in
        Hive.
      displayName: Metering Hive Table
      kind: HiveTable
      name: hivetables.metering.openshift.io
      version: v1
  description: An Ansible-based OpenShift Operator based off of Operator-SDK to create and upload Openshift cost-usage reports to Cost Management
  displayName: Cost Management Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: cost-mgmt-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cost-mgmt-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: cost-mgmt-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/abaiken/cost-mgmt-operator:v0.0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
                - mountPath: /tmp/cost-mgmt-operator-collect
                  name: cost-mgmt-operator
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cost-mgmt-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/abaiken/cost-mgmt-operator:v0.0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                - mountPath: /tmp/cost-mgmt-operator-collect
                  name: cost-mgmt-operator
                - mountPath: /var/run/configmaps/trusted-ca-bundle
                  name: trusted-ca-volume
                  readOnly: true
              serviceAccountName: cost-mgmt-operator
              volumes:
              - emptyDir: {}
                name: runner
              - name: cost-mgmt-operator
              - configMap:
                  name: trusted-ca-bundle
                name: trusted-ca-volume
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - cost-mgmt-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - cost-mgmt.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cost-mgmt-data.openshift.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - metering.openshift.io
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - reportdatasources
          - reportqueries
          - reports
          - meteringconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - list
        serviceAccountName: cost-mgmt-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  replaces: cost-mgmt-operator.v0.0.0
  version: 0.0.1
