---
apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: cm-kube-pod-labels
spec:
  prometheusMetricsImporter:
    query: |
      kube_pod_labels
