---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: cm-pod-persistentvolumeclaim-info-raw
spec:
  reportQueryView:
    queryName: cm-pod-persistentvolumeclaim-info-raw
