---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportDataSource
metadata:
  labels:
    cost-management: "true"
  name: cm-pod-memory-limit-raw
spec:
  reportQueryView:
    queryName: cm-pod-memory-limit-raw
