---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: costmanagements.cost-mgmt.openshift.io
spec:
  group: cost-mgmt.openshift.io
  names:
    kind: CostManagement
    listKind: CostManagementList
    plural: costmanagements
    singular: costmanagement
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - clusterID
            - reporting_operator_token_name
          properties:
            clusterID:
              type: string
            reporting_operator_token_name:
              type: string
            validate_cert:
              type: string
  versions:
    - name: v1alpha1
      served: true
      storage: true
