---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cost-mgmts.cost-mgmt.openshift.io
spec:
  group: cost-mgmt.openshift.io
  names:
    kind: CostManagement
    listKind: CostManagementList
    plural: cost-mgmts
    singular: cost-mgmt
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
    - name: v1alpha1
      served: true
      storage: true
