---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: korekutas.korekuta.example.com
spec:
  group: korekuta.example.com
  names:
    kind: Korekuta
    listKind: KorekutaList
    plural: korekutas
    singular: korekutas
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
    - name: v1alpha1
      served: true
      storage: true
