---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-cost-mgmt-operator
rules:
  - verbs:
      - update
    apiGroups:
      - ''
    resources:
      - services/finalizers
      - deployments/finalizers
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - list
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - proxies
  - verbs:
      - list
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - networks
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
