---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cost-mgmt-operator
subjects:
  - kind: ServiceAccount
    name: cost-mgmt-operator
roleRef:
  kind: Role
  name: cost-mgmt-operator
  apiGroup: rbac.authorization.k8s.io
