---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options: {}
lint: |
  yamllint .
platforms:
  - name: test-cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-openshift-metering}
  lint:
    name: ansible-lint
    enabled: false
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  name: test-cluster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
